### ISSUE TITLE
remove generics from docs

### ISSUE THREAD

**Issue by spockfish** [MvvmCross/mvvmcross-docs#17]
With all respect for those persons that wrote on the generics documentation: it has very little to do with MvvmCross and spends a huge amount of text on explaining generics in general (pun intended). 

I would seriously suggest to remove this page from the documentation: I don't see the point of having an explanation on the generics concept inside the MvvmCross documentation; you can find more than enough documentation on the subject for various languages on the big dirty web.

**Comment by Cheesebaron** [comment]
Yeah, not sure where that doc came from to begin with.

**Comment by Cheesebaron** [comment]
Done, thanks
