### ISSUE TITLE
Header image path needs to be relative

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/mvvmcross-docs#2]
https://github.com/MvvmCross/mvvmcross-docs/blob/master/docs/_includes/header.html#L6

Currently hardcoded to `../img/MvvmCross-logo.png`. This means it is not shown on the index page, because it looks too far behind for the image.

**Comment by MarcBruins** [comment]
agreed, the path to the image should always work

**Comment by MarcBruins** [comment]
done
