### ISSUE TITLE
Code hightlighting

### ISSUE THREAD

**Issue by MarcBruins** [MvvmCross/mvvmcross-docs#23]
On the website there are code blocks which display code. The syntax however is not highlighted and it isnt very clear now. We should include something like https://highlightjs.org/ to have some syntax highlighting to make it more readable.

**Comment by MarcBruins** [comment]
So it seems that the syntax has some "c#" highlighting but its still unclear. I'll have a look at some solutions

**Comment by Cheesebaron** [comment]
https://github.com/vmg/redcarpet we could just change from kramdown to redcarpet. We should investigate whether github-pages supports that.

**Comment by Cheesebaron** [comment]
Jekyll already uses rouge, to generate what is needed for syntax highlighting. It seems like it should be enough to just install a pygment scss file to style it.

**Comment by Cheesebaron** [comment]
Looking in the generated css: https://mvvmcross.github.io/mvvmcross-docs/assets/main.css there is a section with syntax highlighting.

There's some more info at the bottom of: https://jekyllrb.com/docs/templates/

**Comment by MarcBruins** [comment]
I noticed that as wel. The minima theme includes the syntax highlighting scss in its theme(https://github.com/jekyll/minima/blob/master/_sass/minima.scss#L42). Not sure how the pygments works but it seems we can just update the color a bit and it should be good? There is a Visual studio theme here as wel which might be interesting(https://github.com/jwarby/jekyll-pygments-themes/blob/master/vs.css)

**Comment by Cheesebaron** [comment]
I think we just grab that css and add it to our own scss file.

**Comment by Cheesebaron** [comment]
Seems to work ok with the VS theme, we just need to be consistent when we make code blocks.

**Comment by MarcBruins** [comment]
Agreed. Maybe change the background color a bit and then we're done.

**Comment by MarcBruins** [comment]
Done, if the background color is not good we can always change it later.
