### ISSUE TITLE
Categories of the docs

### ISSUE THREAD

**Issue by MarcBruins** [MvvmCross/mvvmcross-docs#24]
The docs menu hides item and shows them if you click on the category. It is unclear for a user what content belongs to what category right now. I can imagine if there is somebody looking at the docs for the first time and want to know about "data-binding" and looks in "getting-started".  Some docs can be moved to other categories, platform -> uwp for example is more of a tutorial then info about mvvmcross and that platform. I also think the "developer-guide" is pretty unclear.

My proposal would be for to changed the categories to something like this:

- getting started
-  - getting started only
-  - intro to mvvm?
- tutorials
-  - current tutorials
- fundamentals
-  - data binding
-  - viewmodel first navigation etc
-  - passing dto's
-  platform specifics
- upgrading
-  - version 3.x -> 4.x
-  - version 4.x -> 5.x
- samples -> click will open samples repo
- plugins
- testing
- contributing
- licensing 

What do you guys think?

**Comment by Cheesebaron** [comment]
Looks good to me.

Just a couple of notes about the categories.

The `_config.yml` contains the order of the, and only the ones present in that file will be printed out, so make sure you add new and remove old categories from there.

Also if you want to order subitems in categories, you can numerate them, so `01-getting-started.md`, `02-intro-to-mvvm.md`.

As for sub-sub items, we dont have anything in place yet. Currently the Jekyll support for this is very limited, there is a bounty out for this, without any external plugins.

**Comment by nmilcoff** [comment]
Can I suggest renaming the category _Platform_ -> _Platform specifics_ and put it after _Fundamentals_? We can write there about presenters (fragments, ...) background modes, push notifications support

**Comment by MarcBruins** [comment]
Good suggestion @nmilcoff i've added it to the suggested list. The numeration seems nice to do @Cheesebaron. Sub-sub items will have to wait until someone comes up with a solution.

**Comment by martijn00** [comment]
I think it would be good to use the top piece like:
```
---
layout: documentation
title: Getting Started with MvvmCross
category: Getting-started
---
```
But then add 
```
---
layout: documentation
title: Getting Started with MvvmCross
category: Getting-started
order: 1
---
```

Otherwise the urls look weird with the number in them.

**Comment by MarcBruins** [comment]
Agreed on the idea above from Martijn, any idea on how to implement that @Cheesebaron?

**Comment by MarcBruins** [comment]
I've made a start on this will submit PR this evening.

**Comment by Cheesebaron** [comment]
Implement what? Order? You just prefix the markdown files in the category with a number. That is the only way currently. Otherwise you would have to do a lot more filtering on the menu, which I don't think is that easy with the mechanism Jekyll provides.

**Comment by MarcBruins** [comment]
Its actually really easy, for example i added "order: 1" to this file: https://github.com/MarcBruins/mvvmcross-docs/blob/master/docs/_documentation/getting-started/getting-started.md 

and added sorting in here: https://github.com/MarcBruins/mvvmcross-docs/blob/master/docs/_includes/documentation-menu.html#L9 and thats it.
